name = "pibiz-ai"
pages_build_output_dir = "public"
compatibility_date = "2026-05-18"

[[kv_namespaces]]
binding = "PIBIZ_DATA"
id = "e97da7108bcc461ab45cc3497cec835b"

[vars]
CONTACT_EMAIL = "info@aimazetechsolutions.com"
WEBSITE_URL = "https://www.aimazetechsolutions.com"
WHATSAPP_NUMBER = "971509768147"
INITIAL_CUSTOMER_COUNT = "286"
INITIAL_CONSULTATION_COUNT = "94"
PI_PAYMENT_AMOUNT = "1"
EMAIL_FROM = "PiBiz AI <info@aimazetechsolutions.com>"
